# Generated by Django 2.1.5 on 2019-01-25 06:29

from django.db import migrations, models
import django.db.models.deletion
import webserver.promseer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_t', models.DateTimeField(auto_created=True)),
                ('last_modified_t', models.DateTimeField(auto_now=True)),
                ('k', models.CharField(max_length=255, verbose_name='metric')),
                ('v', models.CharField(max_length=255, verbose_name='metric')),
            ],
            managers=[
                ('objects', webserver.promseer.models.CommonManager()),
            ],
        ),
        migrations.CreateModel(
            name='PredictModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_t', models.DateTimeField(auto_created=True)),
                ('last_modified_t', models.DateTimeField(auto_now=True)),
                ('model_bin', models.TextField()),
            ],
            managers=[
                ('objects', webserver.promseer.models.CommonManager()),
            ],
        ),
        migrations.CreateModel(
            name='PredictTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_t', models.DateTimeField(auto_created=True)),
                ('metric_encode', models.CharField(max_length=255, verbose_name='metric encode')),
                ('last_modified_t', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('objects', webserver.promseer.models.CommonManager()),
            ],
        ),
        migrations.CreateModel(
            name='RegisterMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=255, verbose_name='metric')),
                ('created_t', models.DateTimeField(auto_now_add=True)),
                ('last_modified_t', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('objects', webserver.promseer.models.CommonManager()),
            ],
        ),
        migrations.AddField(
            model_name='predicttarget',
            name='register_metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promseer.RegisterMetric'),
        ),
        migrations.AddField(
            model_name='predictmodel',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promseer.PredictTarget'),
        ),
        migrations.AddField(
            model_name='label',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promseer.PredictTarget'),
        ),
        migrations.AlterUniqueTogether(
            name='predicttarget',
            unique_together={('register_metric', 'metric_encode')},
        ),
        migrations.AlterIndexTogether(
            name='predicttarget',
            index_together={('register_metric', 'metric_encode')},
        ),
    ]
