# Generated by Django 2.1.5 on 2019-01-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promseer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictmodel',
            name='created_t',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='predictmodel',
            name='model_bin',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='predicttarget',
            name='created_t',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
