# Generated by Django 2.1.5 on 2019-01-28 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promseer', '0002_auto_20190128_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermetric',
            name='name',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='metric'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='label',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label', to='promseer.PredictTarget'),
        ),
    ]
