# Generated by Django 2.1.5 on 2019-01-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promseer', '0003_auto_20190128_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='target',
        ),
        migrations.AddField(
            model_name='predicttarget',
            name='labels',
            field=models.ManyToManyField(to='promseer.Label'),
        ),
    ]
