# Generated by Django 2.1.5 on 2019-01-28 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promseer', '0004_auto_20190128_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predicttarget',
            name='labels',
        ),
        migrations.AddField(
            model_name='label',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='promseer.PredictTarget'),
            preserve_default=False,
        ),
    ]
