# Generated by Django 2.1.5 on 2019-01-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promseer', '0007_auto_20190128_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='created_t',
        ),
        migrations.RemoveField(
            model_name='label',
            name='last_modified_t',
        ),
    ]
