# Generated by Django 2.1.5 on 2019-01-31 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promseer', '0008_auto_20190128_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermetric',
            name='daily_seasonality',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registermetric',
            name='max_v',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='registermetric',
            name='min_v',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='registermetric',
            name='weekly_seasonality',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='predictmodel',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predict_model', to='promseer.PredictTarget'),
        ),
        migrations.AlterField(
            model_name='registermetric',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
    ]
