# Generated by Django 2.1.5 on 2019-01-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promseer', '0009_auto_20190131_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermetric',
            name='max_v',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='registermetric',
            name='min_v',
            field=models.FloatField(default=None, null=True),
        ),
    ]
