# Generated by Django 2.1.5 on 2019-02-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promseer', '0010_auto_20190131_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermetric',
            name='task_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registermetric',
            name='train_status',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
