# Generated by Django 2.1.5 on 2019-02-12 11:10

from django.db import migrations, models
import webserver.promseer.models


class Migration(migrations.Migration):

    dependencies = [
        ('promseer', '0011_auto_20190202_1535'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='registermetric',
            managers=[
                ('objects', webserver.promseer.models.RegisterMetricManager()),
            ],
        ),
        migrations.AddField(
            model_name='registermetric',
            name='predict_period',
            field=models.IntegerField(default=24, verbose_name='hours'),
        ),
        migrations.AddField(
            model_name='registermetric',
            name='train_period',
            field=models.IntegerField(default=24, verbose_name='hours'),
        ),
    ]
