# Generated by Django 2.1.5 on 2019-03-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promseer', '0013_auto_20190214_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermetric',
            name='cron',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
